WIDTH = 10
HEIGHT = 20
SCALE = 30
ELEMENT_SIZE = 28
ELEMENT_RADIUS = 3
FPS = 60
INITIAL_SPEED_DELAY = FPS / 2

SCREEN_COLOR = "black"
SCORE_COLOR = "white"
GAME_OVER_COLOR = "red"
SNAKE_COLOR = "yellow"
APPLE_COLOR = "red"